services:
  #the demo app
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  pdp:
    image: permitio/pdp-v2:latest
    environment:
      - PDP_API_KEY=${PERMIT_API_KEY}
      - PDP_OPA_CLIENT_QUERY_TIMEOUT=60
    ports:
      - "7766:7000"
      - "8181:8181"
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=${NGROK_DOMAIN}"
      - "http://host.docker.internal:3000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:80"
